### ISSUE TITLE
Snd (split&delay) xcs3 version: printouts too verbose, incompat with newer ophyd

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/hxrsnd#99]
The lengthy printouts generated by xcs3 for the snd prevent the scientists from using it.
## Expected Behavior
print as much as the old python did

## Current Behavior
`UserWarning` repeatedly printed in the repr, e.g. for `snd.t1` related to `.value` attribute access

## Your Environment
xcs3

## Scientist contact:
Yanwen Sun (Sanghoon Song)

**Comment by ZLLentz** [comment]
This issue is missing information about when the undesirable printouts happen and isn't explicit enough about what the desired behavior is.

**Comment by silkenelson** [comment]
I've been told by the scientists that there is a "standalone" version of the SnD code that behaves as expected. Contact Yanwen to find out what this fabled "standalone" SnD code is (I'm waiting to her for her confirm she is ok with being the POC, but am pretty sure she will be)

**Comment by Yanwen-Sun** [comment]
The standalone is here: cd ~xcsopr/bin/snd, and you can do ./run_snd. One example is if you do snd.t1, the return is nice and clean with just user/dial values of the motors on tower1, while in xcs3 if will print out too many things.

**Comment by ZLLentz** [comment]
Ok this is a bug in the `hxrsnd` library, rather than a problem of verbosity. We need to go through `hxrsnd` and find hanging references to `.value`, which is deprecated because it causes issues. We need to change all of these instances to `.get()`.

This is not a problem in `run_snd` which uses very old versions of upstream libraries.

Current output in the collapsed section below:
<details>
In [1]: snd.t1
Out[1]: /reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:TTH.DRBV', name='snd_t1_tth_dial', parent='snd_t1_tth', timestamp=1601407276.014709, auto_monitor=False, string=False) (snd_t1_tth_dial.t1.tth.dial) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:TH1.DRBV', name='snd_t1_th1_dial', parent='snd_t1_th1', timestamp=1601411880.19145, auto_monitor=False, string=False) (snd_t1_th1_dial.t1.th1.dial) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:TH2.DRBV', name='snd_t1_th2_dial', parent='snd_t1_th2', timestamp=1601411880.20957, auto_monitor=False, string=False) (snd_t1_th2_dial.t1.th2.dial) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:X.DRBV', name='snd_t1_x_dial', parent='snd_t1_x', timestamp=1601407275.903852, auto_monitor=False, string=False) (snd_t1_x_dial.t1.x.dial) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:L.DRBV', name='snd_t1_L_dial', parent='snd_t1_L', timestamp=631152000.0, auto_monitor=False, string=False) (snd_t1_L_dial.t1.L.dial) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:Y1:REF_POSITION', name='snd_t1_y1_motor_reference_position', parent='snd_t1_y1', timestamp=1601411879.325338, auto_monitor=False, string=False) (snd_t1_y1_motor_reference_position.t1.y1.motor_reference_position) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:Y2:REF_POSITION', name='snd_t1_y2_motor_reference_position', parent='snd_t1_y2', timestamp=1601411879.325668, auto_monitor=False, string=False) (snd_t1_y2_motor_reference_position.t1.y2.motor_reference_position) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:CHI1:REF_POSITION', name='snd_t1_chi1_motor_reference_position', parent='snd_t1_chi1', timestamp=1601411879.326004, auto_monitor=False, string=False) (snd_t1_chi1_motor_reference_position.t1.chi1.motor_reference_position) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:CHI2:REF_POSITION', name='snd_t1_chi2_motor_reference_position', parent='snd_t1_chi2', timestamp=1601411879.014946, auto_monitor=False, string=False) (snd_t1_chi2_motor_reference_position.t1.chi2.motor_reference_position) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:DH:REF_POSITION', name='snd_t1_dh_motor_reference_position', parent='snd_t1_dh', timestamp=1601411879.014972, auto_monitor=False, string=False) (snd_t1_dh_motor_reference_position.t1.dh.motor_reference_position) which has not gotten value from the control system yet.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value


Tower 1
  --------------------------------------------------
  Motor           |    Position    |      Dial
  --------------------------------------------------
  T1 TTH          |     0.001      |    -45.791
  T1 TH1          |     23.186     |    -143.697
  T1 TH2          |     23.186     |    -100.274
  T1 X            |    100.304     |     79.694
  T1 L            |    249.999     |    176.882
  --------------------------------------------------
  Motor           |    Position    |   Reference
  --------------------------------------------------
  T1 Y1           |     0.000      |     0.000
  T1 Y2           |     -0.000     |     0.000
  T1 CHI1         |     0.000      |     0.000
  T1 CHI2         |     0.000      |     0.000
  T1 DH           |     0.000      |     0.000
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:TTH.DRBV', name='snd_t1_tth_dial', parent='snd_t1_tth', value=-45.79142211914062, timestamp=1601407276.014709, auto_monitor=False, string=False) (snd_t1_tth_dial.t1.tth.dial) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:TH1.DRBV', name='snd_t1_th1_dial', parent='snd_t1_th1', value=-143.69738743756318, timestamp=1601411916.875346, auto_monitor=False, string=False) (snd_t1_th1_dial.t1.th1.dial) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:TH2.DRBV', name='snd_t1_th2_dial', parent='snd_t1_th2', value=-100.27374179943223, timestamp=1601411916.893286, auto_monitor=False, string=False) (snd_t1_th2_dial.t1.th2.dial) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:X.DRBV', name='snd_t1_x_dial', parent='snd_t1_x', value=79.69375500000001, timestamp=1601407275.903852, auto_monitor=False, string=False) (snd_t1_x_dial.t1.x.dial) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/aerotech.py:647: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:L.DRBV', name='snd_t1_L_dial', parent='snd_t1_L', value=176.88160000000002, timestamp=631152000.0, auto_monitor=False, string=False) (snd_t1_L_dial.t1.L.dial) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  " "*offset, self.desc, self.position, self.dial.value)
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:Y1:REF_POSITION', name='snd_t1_y1_motor_reference_position', parent='snd_t1_y1', value=0.0, timestamp=1601411879.325338, auto_monitor=False, string=False) (snd_t1_y1_motor_reference_position.t1.y1.motor_reference_position) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:Y2:REF_POSITION', name='snd_t1_y2_motor_reference_position', parent='snd_t1_y2', value=0.0, timestamp=1601411879.325668, auto_monitor=False, string=False) (snd_t1_y2_motor_reference_position.t1.y2.motor_reference_position) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:CHI1:REF_POSITION', name='snd_t1_chi1_motor_reference_position', parent='snd_t1_chi1', value=0.0, timestamp=1601411879.326004, auto_monitor=False, string=False) (snd_t1_chi1_motor_reference_position.t1.chi1.motor_reference_position) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:CHI2:REF_POSITION', name='snd_t1_chi2_motor_reference_position', parent='snd_t1_chi2', value=0.0, timestamp=1601411879.014946, auto_monitor=False, string=False) (snd_t1_chi2_motor_reference_position.t1.chi2.motor_reference_position) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/hxrsnd/attocube.py:103: UserWarning: You have called obj.value on EpicsSignalRO(read_pv='XCS:SND:T1:DH:REF_POSITION', name='snd_t1_dh_motor_reference_position', parent='snd_t1_dh', value=0.0, timestamp=1601411879.014972, auto_monitor=False, string=False) (snd_t1_dh_motor_reference_position.t1.dh.motor_reference_position) which is a non-monitored signal.
We are falling back to calling `.get` and interrogating the underlying control system, however this may cause several other problems:
   1. This property access may take an arbitrarily long time
   2. This property access, which you expect to be read only may change other state in the Signal.
Your options to fix this are:
  - do not use obj.value.
    - If you are using this is in a plan you like want to be using bps.read, bps.rd, bpp.reset_positions_decorator, bpp.reset_positions_wrapper, bpp.relative_set_decorator, or bpp.relative_set_wrapper
    - if you are doing this in an ophyd method use `self.get`
  - set up the Signal to monitor

This behavior will likely change in the future.
  return self.motor_reference_position.value

</details>

**Comment by klauer** [comment]
After #101, this returns to the following:

(Note that the values are garbage - from a simulated IOC)

```
In [3]: snd
Out[3]:
Split and Delay System Status
-----------------------------
Delay Energy:       369962.19
CC Energy:          184988.14
Delay:           -12.806275488474608

Tower 1
  --------------------------------------------------
  Motor           |    Position    |      Dial
  --------------------------------------------------
  T1 TTH          |     1.000      |     1.000
  T1 TH1          |     1.000      |     1.000
  T1 TH2          |     1.000      |     1.000
  T1 X            |     1.000      |     1.000
  T1 L            |     1.000      |     1.000
  --------------------------------------------------
  Motor           |    Position    |   Reference
  --------------------------------------------------
  T1 Y1           |     1.000      |     1.000
  T1 Y2           |     1.000      |     1.000
  T1 CHI1         |     1.000      |     1.000
  T1 CHI2         |     1.000      |     1.000
  T1 DH           |     1.000      |     1.000

Tower 2
  --------------------------------------------------
  Motor           |    Position    |      Dial
  --------------------------------------------------
  T2 TH           |     1.000      |     1.000
  T2 X            |     1.000      |     1.000

Tower 3
  --------------------------------------------------
  Motor           |    Position    |      Dial
  --------------------------------------------------
  T3 TH           |     1.000      |     1.000
  T3 X            |     1.000      |     1.000

Tower 4
  --------------------------------------------------
  Motor           |    Position    |      Dial
  --------------------------------------------------
  T4 TTH          |     1.000      |     1.000
  T4 TH1          |     1.000      |     1.000
  T4 TH2          |     1.000      |     1.000
  T4 X            |     1.000      |     1.000
  T4 L            |     1.000      |     1.000
  --------------------------------------------------
  Motor           |    Position    |   Reference
  --------------------------------------------------
  T4 Y1           |     1.000      |     1.000
  T4 Y2           |     1.000      |     1.000
  T4 CHI1         |     1.000      |     1.000
  T4 CHI2         |     1.000      |     1.000
  T4 DH           |     1.000      |     1.000

Pneumatics
  ----------------------------------
       Device     |     State
  ----------------------------------
  T1 Valve        |      OPEN
  T4 Valve        |      OPEN
  Vacuum Valve    |      OPEN
  T1 Pressure     |      BAD
  T4 Pressure     |      BAD
  Vacuum Pressure |      BAD
```

**Comment by Yanwen-Sun** [comment]
Now this looks good. When will that get updated to the experimental folder?

**Comment by ZLLentz** [comment]
I'll drop it in as a dev package after writing this comment

**Comment by Yanwen-Sun** [comment]
Sounds good. It will be great if you can you can do it before this Saturday.

**Comment by ZLLentz** [comment]
Deployed master to xcs3, current printout:
```
In [1]: snd.t1
Out[1]:

Tower 1
  --------------------------------------------------
  Motor           |    Position    |      Dial
  --------------------------------------------------
  T1 TTH          |     0.001      |    -45.791
  T1 TH1          |     23.186     |    -143.697
  T1 TH2          |     23.186     |    -100.274
  T1 X            |    100.304     |     79.694
  T1 L            |    249.999     |    176.882
  --------------------------------------------------
  Motor           |    Position    |   Reference
  --------------------------------------------------
  T1 Y1           |     -0.000     |     0.000
  T1 Y2           |     0.000      |     0.000
  T1 CHI1         |     0.000      |     0.000
  T1 CHI2         |     -0.001     |     0.000
  T1 DH           |     -0.001     |     0.000

```

**Comment by klauer** [comment]
@Yanwen-Sun would you consider this issue resolved?

**Comment by Yanwen-Sun** [comment]
Yes. Just tested it. Looks great! thanks.

**Comment by klauer** [comment]
Good to hear - thanks. Closing the issue.

**Comment by Yanwen-Sun** [comment]
Hi, in the new python xcs3, we cannot use mvr to move Aerotech motors for example: snd.t1.th1.mvr(0.001)

**Comment by klauer** [comment]
@Yanwen-Sun, I'll update your development installation of hxrsnd in a few minutes to the latest version, which should support `mvr`.

Also, in the future, please open new issues for unrelated items (see here: https://github.com/pcdshub/Bug-Reports-and-Requests/issues/new/choose )

**Comment by Yanwen-Sun** [comment]
Is it getting fixed? I still get the bug.TypeError: move() got an unexpected keyword argument 'log'
